import Testing
@testable import PiSwiftCodingAgent

@Suite("System theme (v0.99.1)")
struct SystemThemeTests {
    private func rgb(_ hex: String) throws -> RgbColorValue { colorToRgb(try parseColor(hex)) }
    private func dracula() throws -> SystemThemeInput {
        try .init(foreground: rgb("#f8f8f2"), background: rgb("#282a36"), palette:
            ["#21222c", "#ff5555", "#50fa7b", "#f1fa8c", "#bd93f9", "#ff79c6", "#8be9fd", "#f8f8f2",
             "#6272a4", "#ff6e6e", "#69ff94", "#ffffa5", "#d6acff", "#ff92df", "#a4ffff", "#ffffff"].map(rgb))
    }
    private func terminals() throws -> [(String, SystemThemeInput)] {
        try [("dracula", dracula()), ("solarizedLight", .init(foreground: rgb("#657b83"), background: rgb("#fdf6e3"))),
             ("backgroundOnly", .init(background: rgb("#1e1e1e"))), ("midGray", .init(foreground: rgb("#ffffff"), background: rgb("#808080")))]
    }
    private let panels = ["userMessageBg", "toolPendingBg", "toolSuccessBg", "toolErrorBg", "selectedBg"]
    private func resolved(_ input: SystemThemeInput, _ token: String) throws -> RgbColorValue {
        switch generateSystemThemeColors(input).colors[token]! {
        case .string(""): return panels.contains(token) ? input.background! : input.foreground!
        case .string(let hex): return try rgb(hex)
        case .number(let index): return colorToRgb(try parseColor(index))
        }
    }
    @Test func bodyTextContrast() throws {
        for (_, input) in try terminals() {
            let text = try resolved(input, "text")
            for surface in [input.background!, try resolved(input, "selectedBg")] { #expect(wcagContrast(text, surface) >= 4.5) }
            #expect(try wcagContrast(resolved(input, "toolTitle"), resolved(input, "toolErrorBg")) >= 4.5)
        }
    }
    @Test func roleOrderAndPanels() throws {
        for (name, input) in try terminals() {
            let background = colorToOklch(.rgb(input.background!)).l
            func offset(_ token: String) throws -> Double { try colorToOklch(.rgb(resolved(input, token))).l - background }
            if name != "midGray" {
                #expect(try abs(offset("text")) > abs(offset("muted")))
                #expect(try abs(offset("muted")) > abs(offset("dim")))
            }
            let lighter = generateSystemThemeColors(input).appearance == .dark
            for panel in panels {
                #expect(try wcagContrast(resolved(input, panel), input.background!) < 2)
                #expect(try (offset(panel) > 0) == lighter)
            }
        }
    }
    @Test func foregroundAndPalette() throws {
        let input = try dracula()
        #expect(generateSystemThemeColors(input).colors["text"] == .string(""))
        #expect(generateSystemThemeColors(try terminals()[1].1).colors["text"] != .string(""))
        #expect(try abs(colorToOklch(.rgb(resolved(input, "error"))).h - colorToOklch(.rgb(input.palette![1])).h) < 8)
    }
    @Test func grayscale() throws {
        var input = try dracula(); input.saturation = 0
        #expect(try colorToOklch(.rgb(resolved(input, "error"))).c < 0.005)
    }
    @Test func noBackground() {
        let result = generateSystemThemeColors(.init(appearanceHint: .light))
        #expect(result.appearance == .light)
        #expect(result.colors["error"] == .number(1))
        #expect(result.colors["text"] == .string(""))
        #expect(result.colors["userMessageBg"] == .string(""))
        #expect(result.dim.contains("muted"))
        #expect(generateSystemThemeColors(.init(saturation: 0)).colors["error"] == .string(""))
    }
    // These values were generated by the tag's TypeScript with Node's type stripping.
    // Upstream v1.0.0 (#10255) caps palette chroma; the Dracula vector is regenerated from the v1.0.0 tag.
    // Each fixture checks all 56 tokens, including palette and relaxation cases.
    @Test func upstreamExactVectors() throws {
        var inputs = try terminals().map { $0.1 }
        var grayscale = try dracula(); grayscale.saturation = 0
        inputs.append(grayscale)
        let expected: [[String: SystemThemeColor]] = [
            [
                "selectedBg": .string("#45236c"),
                "searchMatchBg": .string("#393c04"),
                "userMessageBg": .string("#45236c"),
                "customMessageBg": .string("#670447"),
                "toolPendingBg": .string("#31384c"),
                "toolSuccessBg": .string("#11441e"),
                "toolErrorBg": .string("#5f2220"),
                "text": .string(""),
                "userMessageText": .string(""),
                "customMessageText": .string("#96a2c7"),
                "toolTitle": .string(""),
                "syntaxOperator": .string("#96a2c7"),
                "syntaxPunctuation": .string("#96a2c7"),
                "muted": .string("#96a2c7"),
                "dim": .string("#7484b5"),
                "thinkingText": .string("#8e9cc3"),
                "toolOutput": .string("#96a2c7"),
                "mdLinkUrl": .string("#96a2c7"),
                "mdQuote": .string("#96a2c7"),
                "mdQuoteBorder": .string("#96a2c7"),
                "mdHr": .string("#96a2c7"),
                "mdCodeBlockBorder": .string("#96a2c7"),
                "toolDiffContext": .string("#96a2c7"),
                "syntaxComment": .string("#96a2c7"),
                "scrollbarTrack": .string("#424d6e"),
                "scrollbarThumb": .string("#8f9cc4"),
                "searchMatchText": .string("#96a2c7"),
                "borderMuted": .string("#6c7daf"),
                "accent": .string("#f16cb9"),
                "borderAccent": .string("#ea66b3"),
                "customMessageLabel": .string("#f16dba"),
                "mdCode": .string("#f16dba"),
                "mdListBullet": .string("#f16dba"),
                "syntaxType": .string("#f16dba"),
                "border": .string("#ae85e9"),
                "mdLink": .string("#b58bf0"),
                "syntaxKeyword": .string("#b58bf0"),
                "syntaxVariable": .string("#53b2c6"),
                "success": .string("#39c15c"),
                "mdCodeBlock": .string("#39c15c"),
                "toolDiffAdded": .string("#39c15c"),
                "bashMode": .string("#38b959"),
                "syntaxNumber": .string("#f16dba"),
                "error": .string("#f9756f"),
                "toolDiffRemoved": .string("#f9756f"),
                "warning": .string("#a4ab3b"),
                "mdHeading": .string("#a4ab3b"),
                "syntaxFunction": .string("#a4ab3b"),
                "syntaxString": .string("#39c15c"),
                "thinkingOff": .string("#6272a4"),
                "thinkingMinimal": .string("#8c62c3"),
                "thinkingLow": .string("#9268ca"),
                "thinkingMedium": .string("#3296a8"),
                "thinkingHigh": .string("#d856a3"),
                "thinkingXhigh": .string("#d068b3"),
                "thinkingMax": .string("#ff5555"),
            ],
            [
                "selectedBg": .string("#dfe7eb"),
                "searchMatchBg": .string("#ede3de"),
                "userMessageBg": .string("#dfe7eb"),
                "customMessageBg": .string("#e6e4ee"),
                "toolPendingBg": .string("#e4e6e6"),
                "toolSuccessBg": .string("#dee8e2"),
                "toolErrorBg": .string("#eee3e2"),
                "text": .string("#4a5a60"),
                "userMessageText": .string("#4a5a60"),
                "customMessageText": .string("#677075"),
                "toolTitle": .string("#49595f"),
                "syntaxOperator": .string("#677075"),
                "syntaxPunctuation": .string("#677075"),
                "muted": .string("#677075"),
                "dim": .string("#869095"),
                "thinkingText": .string("#7b858a"),
                "toolOutput": .string("#677075"),
                "mdLinkUrl": .string("#677176"),
                "mdQuote": .string("#677176"),
                "mdQuoteBorder": .string("#677075"),
                "mdHr": .string("#677075"),
                "mdCodeBlockBorder": .string("#677176"),
                "toolDiffContext": .string("#677075"),
                "syntaxComment": .string("#677075"),
                "scrollbarTrack": .string("#e1e2e3"),
                "scrollbarThumb": .string("#97a0a5"),
                "searchMatchText": .string("#677075"),
                "borderMuted": .string("#9aa3a7"),
                "accent": .string("#755ab5"),
                "borderAccent": .string("#8a70ca"),
                "customMessageLabel": .string("#755ab5"),
                "mdCode": .string("#765bb6"),
                "mdListBullet": .string("#765bb6"),
                "syntaxType": .string("#755ab5"),
                "border": .string("#3c8db2"),
                "mdLink": .string("#2f7899"),
                "syntaxKeyword": .string("#2f7798"),
                "syntaxVariable": .string("#287c82"),
                "success": .string("#337f59"),
                "mdCodeBlock": .string("#337f59"),
                "toolDiffAdded": .string("#337f59"),
                "bashMode": .string("#3f966b"),
                "syntaxNumber": .string("#337f59"),
                "error": .string("#c6253c"),
                "toolDiffRemoved": .string("#c6253c"),
                "warning": .string("#8e6701"),
                "mdHeading": .string("#8e6701"),
                "syntaxFunction": .string("#8e6701"),
                "syntaxString": .string("#a65517"),
                "thinkingOff": .string("#c3c7c9"),
                "thinkingMinimal": .string("#b6c3cb"),
                "thinkingLow": .string("#9ec1d4"),
                "thinkingMedium": .string("#a1b6df"),
                "thinkingHigh": .string("#b4a4e8"),
                "thinkingXhigh": .string("#e583cc"),
                "thinkingMax": .string("#fe7177"),
            ],
            [
                "selectedBg": .string("#1f343f"),
                "searchMatchBg": .string("#432a1b"),
                "userMessageBg": .string("#1f343f"),
                "customMessageBg": .string("#332b49"),
                "toolPendingBg": .string("#2e3133"),
                "toolSuccessBg": .string("#21372a"),
                "toolErrorBg": .string("#4a2425"),
                "text": .string("#dddfe0"),
                "userMessageText": .string("#dadcde"),
                "customMessageText": .string("#99a1a6"),
                "toolTitle": .string("#dbddde"),
                "syntaxOperator": .string("#99a1a6"),
                "syntaxPunctuation": .string("#99a1a6"),
                "muted": .string("#99a1a6"),
                "dim": .string("#7a8489"),
                "thinkingText": .string("#919a9f"),
                "toolOutput": .string("#99a1a6"),
                "mdLinkUrl": .string("#98a1a6"),
                "mdQuote": .string("#98a1a6"),
                "mdQuoteBorder": .string("#99a1a6"),
                "mdHr": .string("#99a1a6"),
                "mdCodeBlockBorder": .string("#98a1a6"),
                "toolDiffContext": .string("#99a1a6"),
                "syntaxComment": .string("#99a1a6"),
                "scrollbarTrack": .string("#44494c"),
                "scrollbarThumb": .string("#929ba0"),
                "searchMatchText": .string("#98a1a6"),
                "borderMuted": .string("#727c81"),
                "accent": .string("#a493d6"),
                "borderAccent": .string("#9d8bd4"),
                "customMessageLabel": .string("#a493d6"),
                "mdCode": .string("#a493d6"),
                "mdListBullet": .string("#a493d6"),
                "syntaxType": .string("#a493d6"),
                "border": .string("#57a3c8"),
                "mdLink": .string("#62aacd"),
                "syntaxKeyword": .string("#62aacd"),
                "syntaxVariable": .string("#55b0b7"),
                "success": .string("#61b487"),
                "mdCodeBlock": .string("#61b487"),
                "toolDiffAdded": .string("#61b487"),
                "bashMode": .string("#57ad80"),
                "syntaxNumber": .string("#61b487"),
                "error": .string("#eb777a"),
                "toolDiffRemoved": .string("#eb777a"),
                "warning": .string("#ca961d"),
                "mdHeading": .string("#c9961c"),
                "syntaxFunction": .string("#ca961d"),
                "syntaxString": .string("#dd8751"),
                "thinkingOff": .string("#677176"),
                "thinkingMinimal": .string("#627a86"),
                "thinkingLow": .string("#50849e"),
                "thinkingMedium": .string("#5d81c9"),
                "thinkingHigh": .string("#926fe2"),
                "thinkingXhigh": .string("#dc4abd"),
                "thinkingMax": .string("#fe475a"),
            ],
            [
                "selectedBg": .string("#317c9e"),
                "searchMatchBg": .string("#b45d19"),
                "userMessageBg": .string("#317c9e"),
                "customMessageBg": .string("#7f65c1"),
                "toolPendingBg": .string("#6c767b"),
                "toolSuccessBg": .string("#35835b"),
                "toolErrorBg": .string("#dc2d45"),
                "text": .string("#000000"),
                "userMessageText": .string("#000000"),
                "customMessageText": .string("#000000"),
                "toolTitle": .string("#000000"),
                "syntaxOperator": .string("#000000"),
                "syntaxPunctuation": .string("#000000"),
                "muted": .string("#000000"),
                "dim": .string("#000000"),
                "thinkingText": .string("#000000"),
                "toolOutput": .string("#000000"),
                "mdLinkUrl": .string("#000000"),
                "mdQuote": .string("#000000"),
                "mdQuoteBorder": .string("#000000"),
                "mdHr": .string("#000000"),
                "mdCodeBlockBorder": .string("#000000"),
                "toolDiffContext": .string("#000000"),
                "syntaxComment": .string("#000000"),
                "scrollbarTrack": .string("#60696e"),
                "scrollbarThumb": .string("#000000"),
                "searchMatchText": .string("#000000"),
                "borderMuted": .string("#000000"),
                "accent": .string("#000000"),
                "borderAccent": .string("#000000"),
                "customMessageLabel": .string("#000000"),
                "mdCode": .string("#000000"),
                "mdListBullet": .string("#000000"),
                "syntaxType": .string("#000000"),
                "border": .string("#000000"),
                "mdLink": .string("#000000"),
                "syntaxKeyword": .string("#000000"),
                "syntaxVariable": .string("#000000"),
                "success": .string("#000000"),
                "mdCodeBlock": .string("#000000"),
                "toolDiffAdded": .string("#000000"),
                "bashMode": .string("#000000"),
                "syntaxNumber": .string("#000000"),
                "error": .string("#000000"),
                "toolDiffRemoved": .string("#000000"),
                "warning": .string("#000000"),
                "mdHeading": .string("#000000"),
                "syntaxFunction": .string("#000000"),
                "syntaxString": .string("#000000"),
                "thinkingOff": .string("#3e4345"),
                "thinkingMinimal": .string("#303a40"),
                "thinkingLow": .string("#1f313a"),
                "thinkingMedium": .string("#172133"),
                "thinkingHigh": .string("#000000"),
                "thinkingXhigh": .string("#000000"),
                "thinkingMax": .string("#000000"),
            ],
            [
                "selectedBg": .string("#393939"),
                "searchMatchBg": .string("#393939"),
                "userMessageBg": .string("#393939"),
                "customMessageBg": .string("#393939"),
                "toolPendingBg": .string("#393939"),
                "toolSuccessBg": .string("#393939"),
                "toolErrorBg": .string("#393939"),
                "text": .string(""),
                "userMessageText": .string(""),
                "customMessageText": .string("#a3a3a3"),
                "toolTitle": .string(""),
                "syntaxOperator": .string("#a3a3a3"),
                "syntaxPunctuation": .string("#a3a3a3"),
                "muted": .string("#a3a3a3"),
                "dim": .string("#868686"),
                "thinkingText": .string("#9d9d9d"),
                "toolOutput": .string("#a3a3a3"),
                "mdLinkUrl": .string("#a3a3a3"),
                "mdQuote": .string("#a3a3a3"),
                "mdQuoteBorder": .string("#a3a3a3"),
                "mdHr": .string("#a3a3a3"),
                "mdCodeBlockBorder": .string("#a3a3a3"),
                "toolDiffContext": .string("#a3a3a3"),
                "syntaxComment": .string("#a3a3a3"),
                "scrollbarTrack": .string("#4e4e4e"),
                "scrollbarThumb": .string("#9d9d9d"),
                "searchMatchText": .string("#a3a3a3"),
                "borderMuted": .string("#7f7f7f"),
                "accent": .string("#a3a3a3"),
                "borderAccent": .string("#9d9d9d"),
                "customMessageLabel": .string("#a3a3a3"),
                "mdCode": .string("#a3a3a3"),
                "mdListBullet": .string("#a3a3a3"),
                "syntaxType": .string("#a3a3a3"),
                "border": .string("#9d9d9d"),
                "mdLink": .string("#a3a3a3"),
                "syntaxKeyword": .string("#a3a3a3"),
                "syntaxVariable": .string("#a3a3a3"),
                "success": .string("#a3a3a3"),
                "mdCodeBlock": .string("#a3a3a3"),
                "toolDiffAdded": .string("#a3a3a3"),
                "bashMode": .string("#9d9d9d"),
                "syntaxNumber": .string("#a3a3a3"),
                "error": .string("#a3a3a3"),
                "toolDiffRemoved": .string("#a3a3a3"),
                "warning": .string("#a3a3a3"),
                "mdHeading": .string("#a3a3a3"),
                "syntaxFunction": .string("#a3a3a3"),
                "syntaxString": .string("#a3a3a3"),
                "thinkingOff": .string("#747474"),
                "thinkingMinimal": .string("#7b7b7b"),
                "thinkingLow": .string("#818181"),
                "thinkingMedium": .string("#878787"),
                "thinkingHigh": .string("#8d8d8d"),
                "thinkingXhigh": .string("#939393"),
                "thinkingMax": .string("#999999"),
            ],
        ]
        for (input, values) in zip(inputs, expected) {
            #expect(generateSystemThemeColors(input).colors == values)
        }
    }

}

@Suite("System theme API (v0.99.1)", .serialized)
struct SystemThemeAPITests {
    @Test func listedReservedExportAndTerminalColors() throws {
        defer { setTerminalColors(TerminalColors()) }
        #expect(getAvailableThemes().first == "system")
        let export = getThemeExportColors("system")
        #expect(export.pageBg == nil && export.cardBg == nil && export.infoBg == nil)
        let foreground = colorToRgb(try parseColor("#f8f8f2"))
        let background = colorToRgb(try parseColor("#282a36"))
        let palette = try ["#21222c", "#ff5555", "#50fa7b", "#f1fa8c", "#bd93f9", "#ff79c6", "#8be9fd", "#f8f8f2",
                           "#6272a4", "#ff6e6e", "#69ff94", "#ffffa5", "#d6acff", "#ff92df", "#a4ffff", "#ffffff"].map { colorToRgb(try parseColor($0)) }
        setTerminalColors(.init(foreground: foreground, background: background, palette: palette))
        let theme = try #require(getThemeByName("system"))
        #expect(theme.appearance == .dark)
        #expect(theme.getFgAnsi(.text) == "\u{001B}[39m")
        #expect(theme.getFgAnsi(.error).hasPrefix("\u{001B}[38;"))
    }
    @Test func faintTokens() throws {
        setTerminalColors(TerminalColors())
        let theme = try #require(getThemeByName("system"))
        #expect(theme.fg(.muted, "x") == "\u{001B}[39m\u{001B}[2mx\u{001B}[22;39m")
        #expect(theme.style("x", options: .init(fg: .token(.muted))) == "\u{001B}[39m\u{001B}[2mx\u{001B}[22m\u{001B}[39m")
    }
}
