import Foundation

// This file is auto-generated by Scripts/generate-ai-catalogs.js.
// Do not edit manually.

internal let ClassifierModelsData: [String: [String: ClassifierModel]] = [
    "cloudflare-workers-ai": providerModels_classifier_cloudflare_workers_ai,
    "opencode": providerModels_classifier_opencode,
    "openrouter": providerModels_classifier_openrouter,
    "typesafe": providerModels_classifier_typesafe,
    "vercel-ai-gateway": providerModels_classifier_vercel_ai_gateway,
]

private let providerModels_classifier_cloudflare_workers_ai: [String: ClassifierModel] = [
    "typesafe/jev": ClassifierModel(
        id: "typesafe/jev",
        name: "Jev",
        api: .cloudflareWorkersAISystemOne,
        provider: "cloudflare-workers-ai",
        baseUrl: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
]

private let providerModels_classifier_opencode: [String: ClassifierModel] = [
    "jev-1.13": ClassifierModel(
        id: "jev-1.13",
        name: "Jev 1.13",
        api: .typesafeSystemOne,
        provider: "opencode",
        baseUrl: "https://opencode.ai/zen/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
    "jev-1.13-free": ClassifierModel(
        id: "jev-1.13-free",
        name: "Jev 1.13 Free",
        api: .typesafeSystemOne,
        provider: "opencode",
        baseUrl: "https://opencode.ai/zen/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
]

private let providerModels_classifier_openrouter: [String: ClassifierModel] = [
    "jaredpalmer/kev-4b": ClassifierModel(
        id: "jaredpalmer/kev-4b",
        name: "Jared Palmer: Kev 4B",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 8192
    ),
    "respan/span-01": ClassifierModel(
        id: "respan/span-01",
        name: "Respan: Span-01",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.02, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 4096
    ),
    "respan/span-01-lite": ClassifierModel(
        id: "respan/span-01-lite",
        name: "Respan: Span-01 Lite",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 4096
    ),
    "respan/span-01-lite:free": ClassifierModel(
        id: "respan/span-01-lite:free",
        name: "Respan: Span-01 Lite (free)",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 4096
    ),
    "typesafe/jev-1.13": ClassifierModel(
        id: "typesafe/jev-1.13",
        name: "TypeSafe: Jev 1.13",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
    "upstage/solar-decide": ClassifierModel(
        id: "upstage/solar-decide",
        name: "Upstage: Solar Decide",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.05, output: 0, cacheRead: 0.05, cacheWrite: 0),
        contextWindow: 524288
    ),
    "~typesafe/jev-latest": ClassifierModel(
        id: "~typesafe/jev-latest",
        name: "TypeSafe: Jev Latest",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
]

private let providerModels_classifier_typesafe: [String: ClassifierModel] = [
    "jev-latest": ClassifierModel(
        id: "jev-latest",
        name: "Jev",
        api: .typesafeSystemOne,
        provider: "typesafe",
        baseUrl: "https://api.typesafe.ai/v1/",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 64000
    ),
]

private let providerModels_classifier_vercel_ai_gateway: [String: ClassifierModel] = [
    "liquid/d1": ClassifierModel(
        id: "liquid/d1",
        name: "Liquid d1",
        api: .typesafeSystemOne,
        provider: "vercel-ai-gateway",
        baseUrl: "https://ai-gateway.vercel.sh/typesafe/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
    "typesafe-ai/jev": ClassifierModel(
        id: "typesafe-ai/jev",
        name: "Jev",
        api: .typesafeSystemOne,
        provider: "vercel-ai-gateway",
        baseUrl: "https://ai-gateway.vercel.sh/typesafe/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
]
