import Foundation

// This file is auto-generated by Scripts/generate-ai-catalogs.js.
// Do not edit manually.

internal let ClassifierModelsData: [String: [String: ClassifierModel]] = [
    "cloudflare-workers-ai": providerModels_classifier_cloudflare_workers_ai,
    "openai": providerModels_classifier_openai,
    "opencode": providerModels_classifier_opencode,
    "openrouter": providerModels_classifier_openrouter,
    "typesafe": providerModels_classifier_typesafe,
    "vercel-ai-gateway": providerModels_classifier_vercel_ai_gateway,
]

private let providerModels_classifier_cloudflare_workers_ai: [String: ClassifierModel] = [
    "@cf/cloudflare/clef": ClassifierModel(
        id: "@cf/cloudflare/clef",
        name: "Clef",
        api: .cloudflareWorkersAISystemOne,
        provider: "cloudflare-workers-ai",
        baseUrl: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai",
        input: [.text],
        cost: ModelCost(input: 0.24, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 65536
    ),
    "@cf/cloudflare/clef-flash": ClassifierModel(
        id: "@cf/cloudflare/clef-flash",
        name: "Clef Flash",
        api: .cloudflareWorkersAISystemOne,
        provider: "cloudflare-workers-ai",
        baseUrl: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai",
        input: [.text],
        cost: ModelCost(input: 0.09, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 65536
    ),
    "typesafe/jev": ClassifierModel(
        id: "typesafe/jev",
        name: "Jev",
        api: .cloudflareWorkersAISystemOne,
        provider: "cloudflare-workers-ai",
        baseUrl: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
]

private let providerModels_classifier_openai: [String: ClassifierModel] = [
    "gpt-6-luna": ClassifierModel(
        id: "gpt-6-luna",
        name: "GPT-6 Luna",
        api: .openAIDecisions,
        provider: "openai",
        baseUrl: "https://api.openai.com/v1",
        input: [.text, .image],
        cost: ModelCost(input: 0.1, output: 0, cacheRead: 0, cacheWrite: 0, tiers: [ModelCostTier(inputTokensAbove: 272000, input: 0.2, output: 0, cacheRead: 0, cacheWrite: 0)]),
        contextWindow: 922000
    ),
]

private let providerModels_classifier_opencode: [String: ClassifierModel] = [
    "jev-1.13": ClassifierModel(
        id: "jev-1.13",
        name: "Jev 1.13",
        api: .typesafeSystemOne,
        provider: "opencode",
        baseUrl: "https://opencode.ai/zen/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
    "jev-1.13-free": ClassifierModel(
        id: "jev-1.13-free",
        name: "Jev 1.13 Free",
        api: .typesafeSystemOne,
        provider: "opencode",
        baseUrl: "https://opencode.ai/zen/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
]

private let providerModels_classifier_openrouter: [String: ClassifierModel] = [
    "cloudflare/clef": ClassifierModel(
        id: "cloudflare/clef",
        name: "Cloudflare: Clef",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        cost: ModelCost(input: 0.24, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 65536
    ),
    "cloudflare/clef-flash": ClassifierModel(
        id: "cloudflare/clef-flash",
        name: "Cloudflare: Clef Flash",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        cost: ModelCost(input: 0.021, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 16384
    ),
    "inception/mercury-decide:free": ClassifierModel(
        id: "inception/mercury-decide:free",
        name: "Inception: Mercury Decide (free)",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32768
    ),
    "jaredpalmer/kev-4b": ClassifierModel(
        id: "jaredpalmer/kev-4b",
        name: "Jared Palmer: Kev 4B",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 8192
    ),
    "liquid/d1": ClassifierModel(
        id: "liquid/d1",
        name: "LiquidAI: d1",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.04, output: 0, cacheRead: 0.04, cacheWrite: 0),
        contextWindow: 65536
    ),
    "openai/gpt-6-luna-decisions": ClassifierModel(
        id: "openai/gpt-6-luna-decisions",
        name: "OpenAI: GPT-6 Luna Decisions",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        cost: ModelCost(input: 0.1, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 1050000
    ),
    "perplexity/pplx-decider-v1.1-27b": ClassifierModel(
        id: "perplexity/pplx-decider-v1.1-27b",
        name: "Perplexity: Decider V1.1 27B",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        cost: ModelCost(input: 0.02, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 262144
    ),
    "respan/span-01": ClassifierModel(
        id: "respan/span-01",
        name: "Respan: Span-01",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.02, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 4096
    ),
    "respan/span-01-lite": ClassifierModel(
        id: "respan/span-01-lite",
        name: "Respan: Span-01 Lite",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 4096
    ),
    "respan/span-01-lite:free": ClassifierModel(
        id: "respan/span-01-lite:free",
        name: "Respan: Span-01 Lite (free)",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 4096
    ),
    "togethercomputer/tev1-4b-experimental": ClassifierModel(
        id: "togethercomputer/tev1-4b-experimental",
        name: "Together: Tev1 4B Experimental",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32768
    ),
    "typesafe/jev-1.13": ClassifierModel(
        id: "typesafe/jev-1.13",
        name: "TypeSafe: Jev 1.13",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 64000
    ),
    "upstage/solar-decide": ClassifierModel(
        id: "upstage/solar-decide",
        name: "Upstage: Solar Decide",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.05, output: 0, cacheRead: 0.05, cacheWrite: 0),
        contextWindow: 524288
    ),
    "upstage/solar-decide-flash": ClassifierModel(
        id: "upstage/solar-decide-flash",
        name: "Upstage: Solar Decide Flash",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.05, output: 0, cacheRead: 0.05, cacheWrite: 0),
        contextWindow: 524288
    ),
    "~typesafe/jev-latest": ClassifierModel(
        id: "~typesafe/jev-latest",
        name: "TypeSafe: Jev Latest",
        api: .typesafeSystemOne,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 64000
    ),
]

private let providerModels_classifier_typesafe: [String: ClassifierModel] = [
    "jev-latest": ClassifierModel(
        id: "jev-latest",
        name: "Jev",
        api: .typesafeSystemOne,
        provider: "typesafe",
        baseUrl: "https://api.typesafe.ai/v1/",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 64000
    ),
]

private let providerModels_classifier_vercel_ai_gateway: [String: ClassifierModel] = [
    "convaiinnovations/laya": ClassifierModel(
        id: "convaiinnovations/laya",
        name: "Laya",
        api: .typesafeSystemOne,
        provider: "vercel-ai-gateway",
        baseUrl: "https://ai-gateway.vercel.sh/typesafe/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 8192
    ),
    "convaiinnovations/laya-free": ClassifierModel(
        id: "convaiinnovations/laya-free",
        name: "Laya (Free)",
        api: .typesafeSystemOne,
        provider: "vercel-ai-gateway",
        baseUrl: "https://ai-gateway.vercel.sh/typesafe/v1",
        input: [.text],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 8192
    ),
    "liquid/d1": ClassifierModel(
        id: "liquid/d1",
        name: "Liquid d1",
        api: .typesafeSystemOne,
        provider: "vercel-ai-gateway",
        baseUrl: "https://ai-gateway.vercel.sh/typesafe/v1",
        input: [.text],
        cost: ModelCost(input: 0.04, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 65536
    ),
    "openai/gpt-6-luna-decisions": ClassifierModel(
        id: "openai/gpt-6-luna-decisions",
        name: "GPT-6 Luna Decisions",
        api: .typesafeSystemOne,
        provider: "vercel-ai-gateway",
        baseUrl: "https://ai-gateway.vercel.sh/typesafe/v1",
        input: [.text],
        cost: ModelCost(input: 0.1, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 1050000
    ),
    "typesafe-ai/jev": ClassifierModel(
        id: "typesafe-ai/jev",
        name: "Jev",
        api: .typesafeSystemOne,
        provider: "vercel-ai-gateway",
        baseUrl: "https://ai-gateway.vercel.sh/typesafe/v1",
        input: [.text],
        cost: ModelCost(input: 0.042, output: 0, cacheRead: 0, cacheWrite: 0),
        contextWindow: 32000
    ),
]
