import Foundation

// This file is auto-generated by Scripts/generate-ai-catalogs.js.
// Do not edit manually.

internal let ImageModelsData: [String: [String: ImageModel]] = [
    "openrouter": providerModels_image_openrouter,
]

private let providerModels_image_openrouter: [String: ImageModel] = [
    "black-forest-labs/flux.2-flex": ImageModel(
        id: "black-forest-labs/flux.2-flex",
        name: "Black Forest Labs: FLUX.2 Flex",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "black-forest-labs/flux.2-klein-4b": ImageModel(
        id: "black-forest-labs/flux.2-klein-4b",
        name: "Black Forest Labs: FLUX.2 Klein 4B",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "black-forest-labs/flux.2-max": ImageModel(
        id: "black-forest-labs/flux.2-max",
        name: "Black Forest Labs: FLUX.2 Max",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "black-forest-labs/flux.2-pro": ImageModel(
        id: "black-forest-labs/flux.2-pro",
        name: "Black Forest Labs: FLUX.2 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "bytedance-seed/seedream-4.5": ImageModel(
        id: "bytedance-seed/seedream-4.5",
        name: "ByteDance Seed: Seedream 4.5",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "bytedance-seed/seedream-5-0-lite": ImageModel(
        id: "bytedance-seed/seedream-5-0-lite",
        name: "ByteDance Seed: Seedream 5.0 Lite",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "bytedance-seed/seedream-5-0-pro": ImageModel(
        id: "bytedance-seed/seedream-5-0-pro",
        name: "ByteDance Seed: Seedream 5.0 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "google/gemini-2.5-flash-image": ImageModel(
        id: "google/gemini-2.5-flash-image",
        name: "Google: Nano Banana (Gemini 2.5 Flash Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0.0833333333333333)
    ),
    "google/gemini-3-pro-image": ImageModel(
        id: "google/gemini-3-pro-image",
        name: "Google: Nano Banana Pro (Gemini 3 Pro Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 2, output: 12, cacheRead: 0.19999999999999998, cacheWrite: 0.375)
    ),
    "google/gemini-3-pro-image-preview": ImageModel(
        id: "google/gemini-3-pro-image-preview",
        name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 2, output: 12, cacheRead: 0.19999999999999998, cacheWrite: 0.375)
    ),
    "google/gemini-3.1-flash-image": ImageModel(
        id: "google/gemini-3.1-flash-image",
        name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.5, output: 3, cacheRead: 0, cacheWrite: 0)
    ),
    "google/gemini-3.1-flash-image-preview": ImageModel(
        id: "google/gemini-3.1-flash-image-preview",
        name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.5, output: 3, cacheRead: 0, cacheWrite: 0)
    ),
    "google/gemini-3.1-flash-lite-image": ImageModel(
        id: "google/gemini-3.1-flash-lite-image",
        name: "Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.25, output: 1.5, cacheRead: 0, cacheWrite: 0)
    ),
    "inclusionai/ming-image-0.1-design": ImageModel(
        id: "inclusionai/ming-image-0.1-design",
        name: "inclusionAI: Ming Image 0.1 Design",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "krea/krea-2-large": ImageModel(
        id: "krea/krea-2-large",
        name: "Krea: Krea 2 Large",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "krea/krea-2-medium": ImageModel(
        id: "krea/krea-2-medium",
        name: "Krea: Krea 2 Medium",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "krea/krea-2-medium-turbo": ImageModel(
        id: "krea/krea-2-medium-turbo",
        name: "Krea: Krea 2 Medium Turbo",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "meta/muse-image": ImageModel(
        id: "meta/muse-image",
        name: "Meta: Muse Image",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "microsoft/mai-image-2.5": ImageModel(
        id: "microsoft/mai-image-2.5",
        name: "Microsoft AI: MAI-Image-2.5",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 5, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "microsoft/mai-image-2.5-pro": ImageModel(
        id: "microsoft/mai-image-2.5-pro",
        name: "Microsoft AI: MAI-Image-2.5 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 5, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "microsoft/mai-image-2.6": ImageModel(
        id: "microsoft/mai-image-2.6",
        name: "Microsoft AI: MAI-Image-2.6",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 5, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "microsoft/mai-image-2.6-flash": ImageModel(
        id: "microsoft/mai-image-2.6-flash",
        name: "Microsoft AI: MAI-Image-2.6 Flash",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 1.75, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "openai/gpt-5-image": ImageModel(
        id: "openai/gpt-5-image",
        name: "OpenAI: GPT-5 Image",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 10, output: 10, cacheRead: 1.25, cacheWrite: 0)
    ),
    "openai/gpt-5-image-mini": ImageModel(
        id: "openai/gpt-5-image-mini",
        name: "OpenAI: GPT-5 Image Mini",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 2.5, output: 2, cacheRead: 0.25, cacheWrite: 0)
    ),
    "openai/gpt-5.4-image-2": ImageModel(
        id: "openai/gpt-5.4-image-2",
        name: "OpenAI: GPT-5.4 Image 2",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 8, output: 15, cacheRead: 2, cacheWrite: 0)
    ),
    "openai/gpt-image-1": ImageModel(
        id: "openai/gpt-image-1",
        name: "OpenAI: GPT Image 1",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 10, output: 10, cacheRead: 1.25, cacheWrite: 0)
    ),
    "openai/gpt-image-1-mini": ImageModel(
        id: "openai/gpt-image-1-mini",
        name: "OpenAI: GPT Image 1 Mini",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 2.5, output: 2.5, cacheRead: 0.25, cacheWrite: 0)
    ),
    "openai/gpt-image-2": ImageModel(
        id: "openai/gpt-image-2",
        name: "OpenAI: GPT Image 2",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 8, output: 8, cacheRead: 2, cacheWrite: 0)
    ),
    "openai/gpt-image-2.5-flare": ImageModel(
        id: "openai/gpt-image-2.5-flare",
        name: "OpenAI: GPT Image 2.5 Flare",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 8, output: 8, cacheRead: 2, cacheWrite: 0)
    ),
    "openai/gpt-image-2.5-sunburst": ImageModel(
        id: "openai/gpt-image-2.5-sunburst",
        name: "OpenAI: GPT Image 2.5 Sunburst",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 8, output: 8, cacheRead: 2, cacheWrite: 0)
    ),
    "openrouter/auto": ImageModel(
        id: "openrouter/auto",
        name: "Auto Router",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.text, .image],
        cost: ModelCost(input: -1000000, output: -1000000, cacheRead: 0, cacheWrite: 0)
    ),
    "openrouter/auto-beta": ImageModel(
        id: "openrouter/auto-beta",
        name: "Auto Router (Beta)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.text, .image],
        cost: ModelCost(input: -1000000, output: -1000000, cacheRead: 0, cacheWrite: 0)
    ),
    "qwen/qwen-image-3": ImageModel(
        id: "qwen/qwen-image-3",
        name: "Qwen: Qwen Image 3",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "qwen/qwen-image-3-pro": ImageModel(
        id: "qwen/qwen-image-3-pro",
        name: "Qwen: Qwen Image 3 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v3": ImageModel(
        id: "recraft/recraft-v3",
        name: "Recraft: Recraft V3",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4": ImageModel(
        id: "recraft/recraft-v4",
        name: "Recraft: Recraft V4",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-pro": ImageModel(
        id: "recraft/recraft-v4-pro",
        name: "Recraft: Recraft V4 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-pro-vector": ImageModel(
        id: "recraft/recraft-v4-pro-vector",
        name: "Recraft: Recraft V4 Pro Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-styles": ImageModel(
        id: "recraft/recraft-v4-styles",
        name: "Recraft: Recraft V4 Styles",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-styles-pro": ImageModel(
        id: "recraft/recraft-v4-styles-pro",
        name: "Recraft: Recraft V4 Styles Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-styles-pro-vector": ImageModel(
        id: "recraft/recraft-v4-styles-pro-vector",
        name: "Recraft: Recraft V4 Styles Pro Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-styles-vector": ImageModel(
        id: "recraft/recraft-v4-styles-vector",
        name: "Recraft: Recraft V4 Styles Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-vector": ImageModel(
        id: "recraft/recraft-v4-vector",
        name: "Recraft: Recraft V4 Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1": ImageModel(
        id: "recraft/recraft-v4.1",
        name: "Recraft: Recraft V4.1",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-pro": ImageModel(
        id: "recraft/recraft-v4.1-pro",
        name: "Recraft: Recraft V4.1 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-pro-vector": ImageModel(
        id: "recraft/recraft-v4.1-pro-vector",
        name: "Recraft: Recraft V4.1 Pro Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-utility": ImageModel(
        id: "recraft/recraft-v4.1-utility",
        name: "Recraft: Recraft V4.1 Utility",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-utility-pro": ImageModel(
        id: "recraft/recraft-v4.1-utility-pro",
        name: "Recraft: Recraft V4.1 Utility Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-vector": ImageModel(
        id: "recraft/recraft-v4.1-vector",
        name: "Recraft: Recraft V4.1 Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2-fast": ImageModel(
        id: "sourceful/riverflow-v2-fast",
        name: "Sourceful: Riverflow V2 Fast",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2-pro": ImageModel(
        id: "sourceful/riverflow-v2-pro",
        name: "Sourceful: Riverflow V2 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2.5-fast": ImageModel(
        id: "sourceful/riverflow-v2.5-fast",
        name: "Sourceful: Riverflow V2.5 Fast",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2.5-pro": ImageModel(
        id: "sourceful/riverflow-v2.5-pro",
        name: "Sourceful: Riverflow V2.5 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "x-ai/grok-imagine-image-2.0": ImageModel(
        id: "x-ai/grok-imagine-image-2.0",
        name: "xAI: Grok Imagine Image 2.0",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "x-ai/grok-imagine-image-quality": ImageModel(
        id: "x-ai/grok-imagine-image-quality",
        name: "SpaceXAI: Grok Imagine Image Quality",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
]
