import Foundation

// This file is auto-generated by Scripts/generate-ai-catalogs.js.
// Do not edit manually.

internal let ImageModelsData: [String: [String: ImagesModel]] = [
    "openrouter": providerModels_image_openrouter,
]

private let providerModels_image_openrouter: [String: ImagesModel] = [
    "black-forest-labs/flux.2-flex": ImagesModel(
        id: "black-forest-labs/flux.2-flex",
        name: "Black Forest Labs: FLUX.2 Flex",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "black-forest-labs/flux.2-klein-4b": ImagesModel(
        id: "black-forest-labs/flux.2-klein-4b",
        name: "Black Forest Labs: FLUX.2 Klein 4B",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "black-forest-labs/flux.2-max": ImagesModel(
        id: "black-forest-labs/flux.2-max",
        name: "Black Forest Labs: FLUX.2 Max",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "black-forest-labs/flux.2-pro": ImagesModel(
        id: "black-forest-labs/flux.2-pro",
        name: "Black Forest Labs: FLUX.2 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "bytedance-seed/seedream-4.5": ImagesModel(
        id: "bytedance-seed/seedream-4.5",
        name: "ByteDance Seed: Seedream 4.5",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "google/gemini-2.5-flash-image": ImagesModel(
        id: "google/gemini-2.5-flash-image",
        name: "Google: Nano Banana (Gemini 2.5 Flash Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.3, output: 2.5, cacheRead: 0.03, cacheWrite: 0.0833333333333333)
    ),
    "google/gemini-3-pro-image": ImagesModel(
        id: "google/gemini-3-pro-image",
        name: "Google: Nano Banana Pro (Gemini 3 Pro Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 2, output: 12, cacheRead: 0.19999999999999998, cacheWrite: 0.375)
    ),
    "google/gemini-3-pro-image-preview": ImagesModel(
        id: "google/gemini-3-pro-image-preview",
        name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 2, output: 12, cacheRead: 0.19999999999999998, cacheWrite: 0.375)
    ),
    "google/gemini-3.1-flash-image": ImagesModel(
        id: "google/gemini-3.1-flash-image",
        name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.5, output: 3, cacheRead: 0, cacheWrite: 0)
    ),
    "google/gemini-3.1-flash-image-preview": ImagesModel(
        id: "google/gemini-3.1-flash-image-preview",
        name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.5, output: 3, cacheRead: 0, cacheWrite: 0)
    ),
    "google/gemini-3.1-flash-lite-image": ImagesModel(
        id: "google/gemini-3.1-flash-lite-image",
        name: "Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 0.25, output: 1.5, cacheRead: 0, cacheWrite: 0)
    ),
    "krea/krea-2-large": ImagesModel(
        id: "krea/krea-2-large",
        name: "Krea: Krea 2 Large",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "krea/krea-2-medium": ImagesModel(
        id: "krea/krea-2-medium",
        name: "Krea: Krea 2 Medium",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "krea/krea-2-medium-turbo": ImagesModel(
        id: "krea/krea-2-medium-turbo",
        name: "Krea: Krea 2 Medium Turbo",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "microsoft/mai-image-2.5": ImagesModel(
        id: "microsoft/mai-image-2.5",
        name: "Microsoft: MAI-Image-2.5",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 5, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "microsoft/mai-image-2.5-pro": ImagesModel(
        id: "microsoft/mai-image-2.5-pro",
        name: "Microsoft: MAI-Image-2.5 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 5, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "openai/gpt-5-image": ImagesModel(
        id: "openai/gpt-5-image",
        name: "OpenAI: GPT-5 Image",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 10, output: 10, cacheRead: 1.25, cacheWrite: 0)
    ),
    "openai/gpt-5-image-mini": ImagesModel(
        id: "openai/gpt-5-image-mini",
        name: "OpenAI: GPT-5 Image Mini",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 2.5, output: 2, cacheRead: 0.25, cacheWrite: 0)
    ),
    "openai/gpt-5.4-image-2": ImagesModel(
        id: "openai/gpt-5.4-image-2",
        name: "OpenAI: GPT-5.4 Image 2",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.image, .text],
        output: [.image, .text],
        cost: ModelCost(input: 8, output: 15, cacheRead: 2, cacheWrite: 0)
    ),
    "openai/gpt-image-1": ImagesModel(
        id: "openai/gpt-image-1",
        name: "OpenAI: GPT Image 1",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 10, output: 10, cacheRead: 1.25, cacheWrite: 0)
    ),
    "openai/gpt-image-1-mini": ImagesModel(
        id: "openai/gpt-image-1-mini",
        name: "OpenAI: GPT Image 1 Mini",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 2.5, output: 2.5, cacheRead: 0.25, cacheWrite: 0)
    ),
    "openai/gpt-image-2": ImagesModel(
        id: "openai/gpt-image-2",
        name: "OpenAI: GPT Image 2",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 8, output: 8, cacheRead: 2, cacheWrite: 0)
    ),
    "openrouter/auto": ImagesModel(
        id: "openrouter/auto",
        name: "Auto Router",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.text, .image],
        cost: ModelCost(input: -1000000, output: -1000000, cacheRead: 0, cacheWrite: 0)
    ),
    "openrouter/auto-beta": ImagesModel(
        id: "openrouter/auto-beta",
        name: "Auto Router (Beta)",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.text, .image],
        cost: ModelCost(input: -1000000, output: -1000000, cacheRead: 0, cacheWrite: 0)
    ),
    "qwen/qwen-image-3": ImagesModel(
        id: "qwen/qwen-image-3",
        name: "Qwen: Qwen Image 3",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "qwen/qwen-image-3-pro": ImagesModel(
        id: "qwen/qwen-image-3-pro",
        name: "Qwen: Qwen Image 3 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v3": ImagesModel(
        id: "recraft/recraft-v3",
        name: "Recraft: Recraft V3",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4": ImagesModel(
        id: "recraft/recraft-v4",
        name: "Recraft: Recraft V4",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-pro": ImagesModel(
        id: "recraft/recraft-v4-pro",
        name: "Recraft: Recraft V4 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-pro-vector": ImagesModel(
        id: "recraft/recraft-v4-pro-vector",
        name: "Recraft: Recraft V4 Pro Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4-vector": ImagesModel(
        id: "recraft/recraft-v4-vector",
        name: "Recraft: Recraft V4 Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1": ImagesModel(
        id: "recraft/recraft-v4.1",
        name: "Recraft: Recraft V4.1",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-pro": ImagesModel(
        id: "recraft/recraft-v4.1-pro",
        name: "Recraft: Recraft V4.1 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-pro-vector": ImagesModel(
        id: "recraft/recraft-v4.1-pro-vector",
        name: "Recraft: Recraft V4.1 Pro Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-utility": ImagesModel(
        id: "recraft/recraft-v4.1-utility",
        name: "Recraft: Recraft V4.1 Utility",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-utility-pro": ImagesModel(
        id: "recraft/recraft-v4.1-utility-pro",
        name: "Recraft: Recraft V4.1 Utility Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "recraft/recraft-v4.1-vector": ImagesModel(
        id: "recraft/recraft-v4.1-vector",
        name: "Recraft: Recraft V4.1 Vector",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2-fast": ImagesModel(
        id: "sourceful/riverflow-v2-fast",
        name: "Sourceful: Riverflow V2 Fast",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2-pro": ImagesModel(
        id: "sourceful/riverflow-v2-pro",
        name: "Sourceful: Riverflow V2 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2.5-fast": ImagesModel(
        id: "sourceful/riverflow-v2.5-fast",
        name: "Sourceful: Riverflow V2.5 Fast",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "sourceful/riverflow-v2.5-pro": ImagesModel(
        id: "sourceful/riverflow-v2.5-pro",
        name: "Sourceful: Riverflow V2.5 Pro",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
    "x-ai/grok-imagine-image-quality": ImagesModel(
        id: "x-ai/grok-imagine-image-quality",
        name: "SpaceXAI: Grok Imagine Image Quality",
        api: .openrouterImages,
        provider: "openrouter",
        baseUrl: "https://openrouter.ai/api/v1",
        input: [.text, .image],
        output: [.image],
        cost: ModelCost(input: 0, output: 0, cacheRead: 0, cacheWrite: 0)
    ),
]
